In [31]:
import numpy as np
import pandas as pd

### Pandas
Библиотека для работы с данными (анализ, обработка, очистка, загрузка)
- Основные структуры данных
    - Series - одномерный массив с индексами
    - DataFrame - таблица

[Pandas Documentation](https://pandas.pydata.org/docs/getting_started/index.html#getting-started)

In [32]:
# help(pd.Series)
# help(pd.DataFrame)

In [33]:
my_index = ["USA", "Azerbaijan", "Canada"]

In [34]:
my_data = [1776, 1918, 1867]

In [35]:
my_series = pd.Series(my_data, index=my_index)

In [36]:
my_series

USA           1776
Azerbaijan    1918
Canada        1867
dtype: int64

In [37]:
my_series["Azerbaijan"]

np.int64(1918)

In [38]:
ages = {"Nadir": 45, "Kerim": 20, "Gamida": 20}

In [39]:
pd.Series(ages)

Nadir     45
Kerim     20
Gamida    20
dtype: int64

In [40]:
q1 = {"Japan": 80, "China":450, "India": 200, "USA": 250}
q2 = {"Brazil": 150, "China":500, "India": 220, "USA": 300}


In [41]:
sales_q1 = pd.Series(q1)
sales_q2 = pd.Series(q2)

In [42]:
sales_q1

Japan     80
China    450
India    200
USA      250
dtype: int64

In [43]:
sales_q2

Brazil    150
China     500
India     220
USA       300
dtype: int64

In [44]:
sales_q1.keys()

Index(['Japan', 'China', 'India', 'USA'], dtype='object')

In [45]:
sales_q1.index

Index(['Japan', 'China', 'India', 'USA'], dtype='object')

In [46]:
sales_q1 * 2

Japan    160
China    900
India    400
USA      500
dtype: int64

In [47]:
sales_q1 + sales_q2

Brazil      NaN
China     950.0
India     420.0
Japan       NaN
USA       550.0
dtype: float64

In [48]:
first_half = sales_q1.add(sales_q2, fill_value=0)
first_half

Brazil    150.0
China     950.0
India     420.0
Japan      80.0
USA       550.0
dtype: float64

In [49]:
np.random.seed(42)
my_data = np.random.randint(10, 100, (4, 3))

In [50]:
print(my_data)

[[61 24 81]
 [70 30 92]
 [96 84 84]
 [97 33 12]]


In [51]:
my_index = ["USA", "Azerbaijan", "Canada", "Brazil"]
my_columns = ['Jan', 'Feb', 'Mar']

In [53]:
df = pd.DataFrame(my_data, columns=my_columns, index=my_index)
df

Jan  Feb  Mar
USA          61   24   81
Azerbaijan   70   30   92
Canada       96   84   84
Brazil       97   33   12

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, USA to Brazil
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Jan     4 non-null      int32
 1   Feb     4 non-null      int32
 2   Mar     4 non-null      int32
dtypes: int32(3)
memory usage: 80.0+ bytes


In [55]:
employees_data = pd.read_csv("employees.csv")
employees_data

ID      Name  Age     Country  Salary  ExperienceYears Remote Department
0     1      Lucy   56         USA   30854               15    Yes         IT
1     2  Victoria   46  Azerbaijan   68623               11    Yes         HR
2     3  Benjamin   32     Germany   37392               18     No  Marketing
3     4      Luna   25         USA   85680               13     No    Finance
4     5       Zoe   38      Brazil   76717                5    Yes     Design
..  ...       ...  ...         ...     ...              ...    ...        ...
95   96   Abigail   59         USA   52399               16    Yes    Finance
96   97    Harper   56         USA   76214               18    Yes         IT
97   98      Owen   58      France  116416                4     No     Design
98   99     Ethan   45         USA  100271                8    Yes     Design
99  100   Grayson   24     Germany   74064               11    Yes         HR

[100 rows x 8 columns]

In [56]:
employees_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   ID               100 non-null    int64 
 1   Name             100 non-null    object
 2   Age              100 non-null    int64 
 3   Country          100 non-null    object
 4   Salary           100 non-null    int64 
 5   ExperienceYears  100 non-null    int64 
 6   Remote           100 non-null    object
 7   Department       100 non-null    object
dtypes: int64(4), object(4)
memory usage: 6.4+ KB


In [57]:
employees_data.columns

Index(['ID', 'Name', 'Age', 'Country', 'Salary', 'ExperienceYears', 'Remote',
       'Department'],
      dtype='object')

In [58]:
employees_data.head()

ID      Name  Age     Country  Salary  ExperienceYears Remote Department
0   1      Lucy   56         USA   30854               15    Yes         IT
1   2  Victoria   46  Azerbaijan   68623               11    Yes         HR
2   3  Benjamin   32     Germany   37392               18     No  Marketing
3   4      Luna   25         USA   85680               13     No    Finance
4   5       Zoe   38      Brazil   76717                5    Yes     Design

In [59]:
employees_data.tail()

ID     Name  Age  Country  Salary  ExperienceYears Remote Department
95   96  Abigail   59      USA   52399               16    Yes    Finance
96   97   Harper   56      USA   76214               18    Yes         IT
97   98     Owen   58   France  116416                4     No     Design
98   99    Ethan   45      USA  100271                8    Yes     Design
99  100  Grayson   24  Germany   74064               11    Yes         HR

In [60]:
employees_data.head(9)

ID       Name  Age     Country  Salary  ExperienceYears Remote Department
0   1       Lucy   56         USA   30854               15    Yes         IT
1   2   Victoria   46  Azerbaijan   68623               11    Yes         HR
2   3   Benjamin   32     Germany   37392               18     No  Marketing
3   4       Luna   25         USA   85680               13     No    Finance
4   5        Zoe   38      Brazil   76717                5    Yes     Design
5   6  Sebastian   56       Japan  117092                5    Yes     Design
6   7    Paisley   36      France   80859               12     No    Finance
7   8      Jaxon   40  Azerbaijan   56309               18     No         HR
8   9      Aiden   28      Brazil  117455                7     No     Design

In [61]:
employees_data.tail(3)

ID     Name  Age  Country  Salary  ExperienceYears Remote Department
97   98     Owen   58   France  116416                4     No     Design
98   99    Ethan   45      USA  100271                8    Yes     Design
99  100  Grayson   24  Germany   74064               11    Yes         HR

In [62]:
employees_data["Age"]

0     56
1     46
2     32
3     25
4     38
      ..
95    59
96    56
97    58
98    45
99    24
Name: Age, Length: 100, dtype: int64

In [63]:
employees_data["Age"].mean()

np.float64(37.91)

In [64]:
employees_data["Salary"].mean()

np.float64(72947.8)

In [65]:
employees_data[employees_data["Age"] > 45]

ID         Name  Age     Country  Salary  ExperienceYears Remote  \
0    1         Lucy   56         USA   30854               15    Yes   
1    2     Victoria   46  Azerbaijan   68623               11    Yes   
5    6    Sebastian   56       Japan  117092                5    Yes   
11  12        Riley   53         USA   82662               14    Yes   
12  13       Elijah   57      France   42688                0     No   
18  19       Oliver   47     Germany  119045               16    Yes   
19  20       Evelyn   55      Brazil   64698               16     No   
22  23  Christopher   50     Germany   55184                5     No   
27  28       Thomas   59         USA   79811               13     No   
32  33      Eleanor   54       Japan   41411                2    Yes   
36  37         Leah   56  Azerbaijan   38680                7    Yes   
48  49         Noah   52      Brazil   51918               15     No   
51  52         Ezra   53  Azerbaijan   60306                2     No   
52  53        Dylan   57  Azerbaijan   46646               17    Yes   
56  57      Lillian   59      France   32049               12    Yes   
58  59         Zoey   46  Azerbaijan   50932                0     No   
61  62     Isabella   51         USA  102694               15     No   
63  64        James   53         USA   37400               11     No   
65  66       Adrian   48      Brazil   45151               14     No   
70  71         Lily   57      France   89040               19    Yes   
77  78         Ryan   58      France   91267                7     No   
78  79      Michael   46     Germany   78354               11    Yes   
91  92         John   52     Germany   53328               12    Yes   
92  93       Samuel   52      France  116831               17    Yes   
93  94         Nora   50         USA   33987                9    Yes   
95  96      Abigail   59         USA   52399               16    Yes   
96  97       Harper   56         USA   76214               18    Yes   
97  98         Owen   58      France  116416                4     No   

   Department  
0          IT  
1          HR  
5      Design  
11  Marketing  
12         IT  
18         HR  
19  Marketing  
22         HR  
27     Design  
32         IT  
36         IT  
48  Marketing  
51         IT  
52    Finance  
56  Marketing  
58    Finance  
61         IT  
63    Finance  
65    Finance  
70     Design  
77    Finance  
78     Design  
91    Finance  
92         IT  
93         HR  
95    Finance  
96         IT  
97     Design

In [66]:
employees_data["Country"].value_counts()

Country
USA           22
Azerbaijan    18
France        18
Brazil        17
Japan         14
Germany       11
Name: count, dtype: int64

In [67]:
employees_data.groupby("Country")["Salary"].mean()

Country
Azerbaijan    72012.555556
Brazil        76001.882353
France        85016.111111
Germany       62115.000000
Japan         72384.214286
USA           67254.000000
Name: Salary, dtype: float64

In [68]:
employees_data.index

RangeIndex(start=0, stop=100, step=1)

In [69]:
employees_data.describe()

ID         Age        Salary  ExperienceYears
count  100.000000  100.000000     100.00000       100.000000
mean    50.500000   37.910000   72947.80000         9.560000
std     29.011492   12.219454   27241.56386         6.075817
min      1.000000   18.000000   30854.00000         0.000000
25%     25.750000   26.750000   49860.50000         4.000000
50%     50.500000   38.000000   73540.00000        10.000000
75%     75.250000   46.250000   95972.25000        15.000000
max    100.000000   59.000000  119045.00000        19.000000

[Квартиль](https://en.wikipedia.org/wiki/Quartile)

In [70]:
employees_data.describe().transpose()

count      mean           std      min       25%      50%  \
ID               100.0     50.50     29.011492      1.0     25.75     50.5   
Age              100.0     37.91     12.219454     18.0     26.75     38.0   
Salary           100.0  72947.80  27241.563860  30854.0  49860.50  73540.0   
ExperienceYears  100.0      9.56      6.075817      0.0      4.00     10.0   

                      75%       max  
ID                  75.25     100.0  
Age                 46.25      59.0  
Salary           95972.25  119045.0  
ExperienceYears     15.00      19.0

In [73]:
employees_data[["Country", "Name"]]

Country      Name
0          USA      Lucy
1   Azerbaijan  Victoria
2      Germany  Benjamin
3          USA      Luna
4       Brazil       Zoe
..         ...       ...
95         USA   Abigail
96         USA    Harper
97      France      Owen
98         USA     Ethan
99     Germany   Grayson

[100 rows x 2 columns]

In [79]:
new_data = employees_data.drop("Country", axis=1)

In [80]:
new_data

ID      Name  Age  Salary  ExperienceYears Remote Department
0     1      Lucy   56   30854               15    Yes         IT
1     2  Victoria   46   68623               11    Yes         HR
2     3  Benjamin   32   37392               18     No  Marketing
3     4      Luna   25   85680               13     No    Finance
4     5       Zoe   38   76717                5    Yes     Design
..  ...       ...  ...     ...              ...    ...        ...
95   96   Abigail   59   52399               16    Yes    Finance
96   97    Harper   56   76214               18    Yes         IT
97   98      Owen   58  116416                4     No     Design
98   99     Ethan   45  100271                8    Yes     Design
99  100   Grayson   24   74064               11    Yes         HR

[100 rows x 7 columns]

In [81]:
employees_data.drop("Country", axis=1, inplace=True)

In [82]:
employees_data

ID      Name  Age  Salary  ExperienceYears Remote Department
0     1      Lucy   56   30854               15    Yes         IT
1     2  Victoria   46   68623               11    Yes         HR
2     3  Benjamin   32   37392               18     No  Marketing
3     4      Luna   25   85680               13     No    Finance
4     5       Zoe   38   76717                5    Yes     Design
..  ...       ...  ...     ...              ...    ...        ...
95   96   Abigail   59   52399               16    Yes    Finance
96   97    Harper   56   76214               18    Yes         IT
97   98      Owen   58  116416                4     No     Design
98   99     Ethan   45  100271                8    Yes     Design
99  100   Grayson   24   74064               11    Yes         HR

[100 rows x 7 columns]

In [83]:
employees_data.shape

(100, 7)

In [86]:
employees_data2 = pd.read_csv("employeesisnull.csv")

In [87]:
employees_data2

ID      Name  Age     Country    Salary  ExperienceYears Remote  \
0     1      Lucy   56         USA   30854.0               15    Yes   
1     2  Victoria   46  Azerbaijan   68623.0               11    Yes   
2     3  Benjamin   32     Germany   37392.0               18     No   
3     4      Luna   25         USA   85680.0               13     No   
4     5       Zoe   38      Brazil   76717.0                5    Yes   
..  ...       ...  ...         ...       ...              ...    ...   
95   96   Abigail   59         USA   52399.0               16    Yes   
96   97    Harper   56         USA   76214.0               18    Yes   
97   98      Owen   58      France  116416.0                4     No   
98   99     Ethan   45         USA  100271.0                8    Yes   
99  100   Grayson   24     Germany   74064.0               11    Yes   

   Department  
0          IT  
1         NaN  
2   Marketing  
3     Finance  
4      Design  
..        ...  
95    Finance  
96         IT  
97     Design  
98     Design  
99         HR  

[100 rows x 8 columns]

In [89]:
employees_data2.isna().sum()

ID                 0
Name               0
Age                0
Country            2
Salary             1
ExperienceYears    0
Remote             3
Department         2
dtype: int64

In [90]:
employees_data2.dropna()

ID       Name  Age  Country    Salary  ExperienceYears Remote Department
0     1       Lucy   56      USA   30854.0               15    Yes         IT
2     3   Benjamin   32  Germany   37392.0               18     No  Marketing
3     4       Luna   25      USA   85680.0               13     No    Finance
4     5        Zoe   38   Brazil   76717.0                5    Yes     Design
5     6  Sebastian   56    Japan  117092.0                5    Yes     Design
..  ...        ...  ...      ...       ...              ...    ...        ...
95   96    Abigail   59      USA   52399.0               16    Yes    Finance
96   97     Harper   56      USA   76214.0               18    Yes         IT
97   98       Owen   58   France  116416.0                4     No     Design
98   99      Ethan   45      USA  100271.0                8    Yes     Design
99  100    Grayson   24  Germany   74064.0               11    Yes         HR

[92 rows x 8 columns]

In [93]:
employees_data2.fillna(0, inplace=True)

In [94]:
employees_data2

ID      Name  Age     Country    Salary  ExperienceYears Remote  \
0     1      Lucy   56         USA   30854.0               15    Yes   
1     2  Victoria   46  Azerbaijan   68623.0               11    Yes   
2     3  Benjamin   32     Germany   37392.0               18     No   
3     4      Luna   25         USA   85680.0               13     No   
4     5       Zoe   38      Brazil   76717.0                5    Yes   
..  ...       ...  ...         ...       ...              ...    ...   
95   96   Abigail   59         USA   52399.0               16    Yes   
96   97    Harper   56         USA   76214.0               18    Yes   
97   98      Owen   58      France  116416.0                4     No   
98   99     Ethan   45         USA  100271.0                8    Yes   
99  100   Grayson   24     Germany   74064.0               11    Yes   

   Department  
0          IT  
1           0  
2   Marketing  
3     Finance  
4      Design  
..        ...  
95    Finance  
96         IT  
97     Design  
98     Design  
99         HR  

[100 rows x 8 columns]

In [104]:
employees_data.loc[[1, 3, 5], ["Department", "Name", "Salary"]]

Department       Name  Salary
1         HR   Victoria   68623
3    Finance       Luna   85680
5     Design  Sebastian  117092

In [105]:
employees_data.loc[3:7, ["Department", "Name", "Salary"]]

Department       Name  Salary
3    Finance       Luna   85680
4     Design        Zoe   76717
5     Design  Sebastian  117092
6    Finance    Paisley   80859
7         HR      Jaxon   56309

In [108]:
employees_data.iloc[5]

ID                         6
Name               Sebastian
Age                       56
Salary                117092
ExperienceYears            5
Remote                   Yes
Department            Design
Name: 5, dtype: object

In [110]:
employees_data.set_index("Name", inplace=True)

In [111]:
employees_data

ID  Age  Salary  ExperienceYears Remote Department
Name                                                         
Lucy        1   56   30854               15    Yes         IT
Victoria    2   46   68623               11    Yes         HR
Benjamin    3   32   37392               18     No  Marketing
Luna        4   25   85680               13     No    Finance
Zoe         5   38   76717                5    Yes     Design
...       ...  ...     ...              ...    ...        ...
Abigail    96   59   52399               16    Yes    Finance
Harper     97   56   76214               18    Yes         IT
Owen       98   58  116416                4     No     Design
Ethan      99   45  100271                8    Yes     Design
Grayson   100   24   74064               11    Yes         HR

[100 rows x 6 columns]

In [112]:
employees_data.loc["Luna"]

ID                       4
Age                     25
Salary               85680
ExperienceYears         13
Remote                  No
Department         Finance
Name: Luna, dtype: object

In [113]:
employees_data.iloc[3]

ID                       4
Age                     25
Salary               85680
ExperienceYears         13
Remote                  No
Department         Finance
Name: Luna, dtype: object