In [1]:
import torch

### Тензор
1. Скаляр - одно число - 0 мерный массив
2. Вектор - список чисел - 1 мерный массив
3. Матрица - 2 мерный массив
4. Изображение (RGB) - 3 мерный массив
5. Пачка изображений - 4 мерный массив

In [2]:
scalar = torch.tensor(65)
print(f"Scalar {scalar}, Shape: {scalar.shape}")

vector = torch.tensor([6, 5, 4, 32])
print(f"Vector {vector}, Shape: {vector.shape}")

matrix = torch.tensor([[25, 665], [23,44], [35, 52]])
print(f"Matrix {matrix}, Shape: {matrix.shape}")

tensor3D = torch.randn(5, 5, 5)
print(f"Tensor3D {tensor3D}, Shape: {tensor3D.shape}")

Scalar 65, Shape: torch.Size([])
Vector tensor([ 6,  5,  4, 32]), Shape: torch.Size([4])
Matrix tensor([[ 25, 665],
        [ 23,  44],
        [ 35,  52]]), Shape: torch.Size([3, 2])
Tensor3D tensor([[[ 0.3631,  0.0040, -0.5577,  0.4296, -0.4473],
         [-1.7818,  1.3954, -2.2000, -0.7635, -1.2740],
         [-0.0489,  1.3349,  0.3082, -0.5809,  1.0967],
         [ 0.2139, -2.1435,  0.9605, -0.9326,  0.4718],
         [ 0.4927,  0.0257,  0.3522,  1.0473, -1.6250]],

        [[-0.6051, -0.4630,  0.4077,  1.1027,  1.5772],
         [ 0.8774, -1.1014,  1.0903, -1.2039, -0.2684],
         [ 1.6517,  0.3877, -0.7889,  0.4963,  2.5732],
         [-0.9016,  1.1964, -1.5627, -0.6994, -0.6168],
         [ 0.2597, -1.8191,  0.5660, -1.2587,  0.4825]],

        [[ 1.7850,  1.4518, -0.4867,  1.0437, -2.9704],
         [ 0.5089,  0.3078, -0.8480, -0.2582, -0.2855],
         [ 0.1664,  0.0330,  0.2511, -0.3189, -1.0683],
         [-0.4707, -0.1704,  0.6989, -1.5503,  1.3080],
         [ 0.4463, 

In [3]:
# tensor generate
print(torch.zeros(5, 5))
print(torch.ones(5, 5))
print(torch.rand(5, 5))
print(torch.arange(0, 20, 2))

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[0.9790, 0.1245, 0.7935, 0.3188, 0.5724],
        [0.2476, 0.4445, 0.3539, 0.6790, 0.4725],
        [0.3679, 0.8688, 0.6726, 0.7180, 0.8795],
        [0.2283, 0.8544, 0.6629, 0.6542, 0.2592],
        [0.8930, 0.3943, 0.4903, 0.4241, 0.7200]])
tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])


In [4]:
# math operations
a = torch.tensor([1,2,3,4])
b = torch.tensor([5,6,7,8])
print(a+b) # сложение
print(a*b) # покомпонентное умножение
print(torch.dot(a, b)) # Скалярное произведение

tensor([ 6,  8, 10, 12])
tensor([ 5, 12, 21, 32])
tensor(70)


In [5]:
A = torch.tensor([[1,2],[3,4]])
B = torch.tensor([[5,6],[7,8]])
print(A@B)

tensor([[19, 22],
        [43, 50]])


In [6]:
if torch.cuda.is_available():
    device = "cuda"
else:
    device = "cpu"
print(device)

cuda


In [8]:
print(torch.version.cuda)
print(torch.cuda.get_device_name(0))

11.8
NVIDIA GeForce GTX 1080
