In [1]:
import numpy as np

In [2]:
mylist = [25, 78, 7]
type(mylist)

list

In [3]:
np.array(mylist)

array([25, 78,  7])

In [4]:
my_array = np.array(mylist)

In [6]:
type(my_array)

numpy.ndarray

In [7]:
my_matrix = [[25, 96, 20],[56, 98, 45],[36, 77, 91]]
type(my_matrix)

list

In [8]:
np.arange(0, 20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [13]:
print(np.array(my_matrix))


[[25 96 20]
 [56 98 45]
 [36 77 91]]


In [14]:
print(my_matrix)

[[25, 96, 20], [56, 98, 45], [36, 77, 91]]


In [15]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [18]:
arr = np.zeros((5, 6))

In [19]:
print(arr)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [20]:
arr2 = np.ones((5, 6))
print(arr2)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [27]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [28]:
np.linspace(0, 10, 10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [30]:
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [33]:
print(np.eye(5, k=1))

[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]


In [35]:
np.random.rand(5)

array([0.29758019, 0.12646099, 0.14413257, 0.28329175, 0.63691713])

In [36]:
print(np.random.rand(5, 5))

[[0.39681135 0.53015856 0.03228786 0.47502752 0.74857613]
 [0.47642933 0.48075136 0.90370744 0.57838982 0.92043459]
 [0.57392612 0.85638925 0.21002367 0.04109572 0.98936952]
 [0.32535566 0.88397097 0.29655444 0.9524884  0.90959698]
 [0.65021858 0.68817083 0.85756501 0.05766617 0.30328324]]


In [37]:
np.random.randn(5)

array([ 1.62501772,  0.25161702, -1.04522442,  1.54261866, -0.35013364])

In [40]:
np.random.randint(5, 15, 5)

array([13,  8, 10, 13,  5], dtype=int32)

In [42]:
print(np.random.randint(5, 15, (5, 5)))

[[ 7 13 11  9  9]
 [ 6 11 12 14  9]
 [14 12  5 10 11]
 [ 8 12  6 14 13]
 [14 14 13  5  6]]


In [46]:
np.random.seed(42)
np.random.rand(5)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])

In [52]:
arr = np.arange(0, 25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [53]:
arr = arr.reshape(5, 5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [54]:
rand_arr = np.random.randint(0, 500, 20)

In [55]:
rand_arr

array([466, 214, 330, 458,  87, 372,  99, 359, 151, 130, 149, 308, 257,
       343, 491, 413, 293, 385, 191, 443], dtype=int32)

In [56]:
rand_arr.max()

np.int32(491)

In [57]:
rand_arr.min()

np.int32(87)

In [58]:
rand_arr.argmax()

np.int64(14)

In [59]:
rand_arr.argmin()

np.int64(4)

In [60]:
rand_arr.dtype

dtype('int32')