In [37]:
import numpy as np

In [38]:
arr = np.arange(11)

In [39]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
arr[5]

np.int64(5)

In [41]:
arr[0:6]

array([0, 1, 2, 3, 4, 5])

In [42]:
arr[0:6:2]

array([0, 2, 4])

In [43]:
arr[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
arr[:9]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [45]:
arr[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [46]:
arr[:4] = 21
arr

array([21, 21, 21, 21,  4,  5,  6,  7,  8,  9, 10])

In [47]:
slice_arr = arr[4:7]

slice_arr

array([4, 5, 6])

In [48]:
slice_arr[:] = -56
slice_arr

array([-56, -56, -56])

In [49]:
arr

array([ 21,  21,  21,  21, -56, -56, -56,   7,   8,   9,  10])

In [50]:
arr_2d = np.random.randint(10, 99, (6, 7))

In [51]:
print(arr_2d)

[[22 50 25 33 65 44 40]
 [89 66 11 95 59 79 58]
 [31 44 34 69 68 28 70]
 [96 35 44 89 60 44 59]
 [46 86 33 67 85 60 64]
 [89 75 70 32 88 10 86]]


In [52]:
arr_2d[0]

array([22, 50, 25, 33, 65, 44, 40], dtype=int32)

In [54]:
arr_2d[2,3]

np.int32(69)

In [55]:
print(arr_2d[:3])

[[22 50 25 33 65 44 40]
 [89 66 11 95 59 79 58]
 [31 44 34 69 68 28 70]]


In [56]:
print(arr_2d)

[[22 50 25 33 65 44 40]
 [89 66 11 95 59 79 58]
 [31 44 34 69 68 28 70]
 [96 35 44 89 60 44 59]
 [46 86 33 67 85 60 64]
 [89 75 70 32 88 10 86]]


In [57]:
print(arr_2d[:3, 2:])

[[25 33 65 44 40]
 [11 95 59 79 58]
 [34 69 68 28 70]]


In [58]:
arr = np.random.randint(10, 99, 10)
arr

array([95, 68, 88, 29, 72, 62, 24, 98, 78, 19], dtype=int32)

In [61]:
bool_arr = arr < 45
bool_arr

array([False, False, False,  True, False, False,  True, False, False,
        True])

In [62]:
arr[bool_arr]

array([29, 24, 19], dtype=int32)

In [66]:
arr[bool_arr] = -50
arr

array([-50,  68, -50, -50,  72,  62, -50, -50,  78, -50], dtype=int32)