In [1]:
import numpy as np

In [3]:
arr = np.random.randint(10, 99, 10)
arr

array([32, 37, 90, 47, 75, 39, 61, 80, 90, 80], dtype=int32)

In [4]:
arr + 10

array([ 42,  47, 100,  57,  85,  49,  71,  90, 100,  90], dtype=int32)

In [5]:
arr - 2

array([30, 35, 88, 45, 73, 37, 59, 78, 88, 78], dtype=int32)

In [6]:
arr + arr

array([ 64,  74, 180,  94, 150,  78, 122, 160, 180, 160], dtype=int32)

In [7]:
arr * arr

array([1024, 1369, 8100, 2209, 5625, 1521, 3721, 6400, 8100, 6400],
      dtype=int32)

In [9]:
arr / arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
2/arr

array([0.0625    , 0.05405405, 0.02222222, 0.04255319, 0.02666667,
       0.05128205, 0.03278689, 0.025     , 0.02222222, 0.025     ])

In [11]:
np.sqrt(arr)

array([5.65685425, 6.08276253, 9.48683298, 6.8556546 , 8.66025404,
       6.244998  , 7.81024968, 8.94427191, 9.48683298, 8.94427191])

In [12]:
np.sin(arr)

array([ 0.55142668, -0.64353813,  0.89399666,  0.12357312, -0.38778164,
        0.96379539, -0.96611777, -0.99388865,  0.89399666, -0.99388865])

In [13]:
np.log(arr)

array([3.4657359 , 3.61091791, 4.49980967, 3.8501476 , 4.31748811,
       3.66356165, 4.11087386, 4.38202663, 4.49980967, 4.38202663])

In [14]:
arr.sum()

np.int64(631)

In [15]:
arr.mean()

np.float64(63.1)

In [16]:
arr.var()

np.float64(465.28999999999996)

In [17]:
arr.std()

np.float64(21.570581818764182)

[numpy site](https://numpy.org/doc/stable/user/absolute_beginners.html)