In [1]:
import numpy as np

In [2]:
mylist = [25, 78, 7]
type(mylist)

list

In [3]:
np.array(mylist)

array([25, 78,  7])

In [4]:
my_array = np.array(mylist)

In [6]:
type(my_array)

numpy.ndarray

In [7]:
my_matrix = [[25, 96, 20],[56, 98, 45],[36, 77, 91]]
type(my_matrix)

list

In [8]:
np.arange(0, 20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [11]:
np.array(my_matrix)


array([[25, 96, 20],
       [56, 98, 45],
       [36, 77, 91]])